# ruff: noqa: F401
from features.experiment.paths import EXPERIMENT
from features.gallery.paths import GALLERY
from features.home.paths import HOME
from features.index.paths import INDEX
from features.master.paths import MASTER
from features.notifications.paths import NOTIFICATIONS
from features.profile.paths import PROFILE
from features.settings.paths import SETTINGS
